#!/bin/bash


file_input=teams.lis

while read line
do
  # verarbeite nur die Zeilen mit einem Namen
  echo $line | grep -E '^[a-zA-Z-]+, [a-zA-Z-]' > /dev/null || continue

  # hole Namen 
  first=$(echo $line | cut -d' ' -f2)
  last=$(echo $line | cut -d, -f1)

  # erzeuge login
  login=$(echo ${last:0:2}${first:0:2} | sed -e 's/ä/a/g' -e 's/ö/o/g' -e 's/ü/u/g' -e 's/Ä/A/g' -e 's/Ü/U/g' -e 's/Ö/O/g' | tr [:upper:] [:lower:])
  echo $login

  pass=$(dd if=/dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 12)
  phash=$(openssl passwd -6 $pass)
  useradd -md "/home/$login" -g user -G itadh -p $phash -s /bin/bash -c "${first} ${last}" $login
  echo $pass >> "/home/${login}/.pw"

done < $file_input




