#!/bin/bash
#
# autor: jz@drheuer.de
# date: 13.06.2022
#
# description: ermittelt alle IPv4 Adressen in einer Logdatei
#

regex_ipv4='([0-9]{1,2}|[01][0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]{1,2}|[01][0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]{1,2}|[01][0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]{1,2}|[01][0-9]{2}|2[0-4][0-9]|25[0-5])'
myresult=''

# lade functions
. lib/functions

read -p 'Welche Logdatei soll eingelesen werden: ' file_log
counter=0
while read line
do
  # gibt es eine IPv4 Adresse in der Zeile
  have_ipv4 "${regex_ipv4}" "${line}"
  result=$?
  if test $result -eq 0
  then
    counter=$((counter+1))
    # hole die IPv4 Adressen einer Zeile, es koennen mehrere sein.
    # Die Funktion speicher die IP Adressen in der globalen Variable
    # myresult
    get_ipv4 "${regex_ipv4}" "${line}"
  fi
done < "${file_log}"
echo -e "$myresult"
echo $counter

