#!/bin/bash

test $1 || echo 'Bitte die gewünschte Aktion angeben [add|del]' 
test $1 || exit 1

test "$1" == 'add' && action='add'
test "$1" == 'del' && action='del'


file_input=teams.lis

function user_make () {

  local login=$1
  local first=$2
  local last=$3

  echo $login
  echo $first
  echo $last

#  pass=$(dd if=/dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 12)
#  phash=$(openssl passwd -6 $pass)
#  useradd -md "/home/$login" -g user -G itadh -p $phash -s /bin/bash -c "${first} ${last}" $login
#  echo $pass >> "/home/${login}/.pw"

}


function user_del () {
  local $login
    echo $login
#  userdel -rf $login
}

while read line
do
  # verarbeite nur die Zeilen mit einem Namen
  echo $line | grep -E '^[a-zA-Z-]+, [a-zA-Z-]' > /dev/null || continue

  # hole Namen 
  first=$(echo $line | cut -d' ' -f2)
  last=$(echo $line | cut -d, -f1)

  # erzeuge login
  login=$(echo ${last:0:2}${first:0:2} | sed -e 's/ä/a/g' -e 's/ö/o/g' -e 's/ü/u/g' -e 's/Ä/A/g' -e 's/Ü/U/g' -e 's/Ö/O/g' | tr [:upper:] [:lower:])

  # existiert der Benutzer schon
  id $login > /dev/null 2>&1
  test $? -ne 0 && test "$action" == 'add' && user_make $login $first $last

  # existiert der Benutzer schon
  id $login > /dev/null 2>&1
  test $? -eq 0 && test "$action" == 'del' && user_del $login

done < $file_input


