#!/usr/bin/bash

# der Benutzer hat keine Eingabe gemacht
test -z "$1" && echo "Bitte Pfad eingeben" && exit 2 

# wechsel ins Verzeichnis
test -d "$1" || mkdir $1 && cd $1

# tauche die Eltern shell gegen ein neu aus
exec bash

# ende
exit 0

