#!/usr/bin/bash
# author      J.Zimmermann <jz@mgeg.de>
# modified    2020-11-16
# description wechselt ein Verzeichnis und legt es bei Bedarf neu an

__version=1.1.0

# der Benutzer hat keine Eingabe gemacht
test -z "$1" && read -p "Geben Sie einen Pfad an: " dir || dir=$1

# wechsel ins Verzeichnis
test -d "$dir" || mkdir $dir && cd $dir

# tauche die Eltern shell gegen ein neu aus
exec bash

# ende
exit 0

