#!/usr/bin/bash

zaehler=0
IFS=':'
while read login pass uid gid gecos home shell 
do 
  test $uid -gt 1000 || continue
  zaehler=$((zaehler+1))
  group=$(id -gn $login)
  sgroup=$(id -Gn $login)

  echo -e "\n######### ${zaehler} #############"
  echo "User: ${login}"
  echo "Uid: ${uid}"
  echo "Home: ${home}"
  echo "Shell: ${shell}"
  echo "primäre Gruppe: ${group}"
  echo "Sekundäre Gruppe: ${sgroup}"

done < /etc/passwd

echo "Ende Gelände"

