#!/usr/bin/bash

zaehler=0
while read line
do 
 
  uid=$(echo $line | cut -d: -f3)
  test $uid -gt 1000 || continue
#  test $(echo $line | cut -d: -f3) -gt 1000 || continue
  zaehler=$((zaehler+1))
  echo "Zeile ${zaehler} für userid ${uid}: $line"

done < /etc/passwd

echo "Ende Gelände"

