#!/usr/bin/bash

zaehler=0
IFS=':'
while read login pass uid gid gecos home shell 
do 
  test $uid -gt 1000 || continue
  zaehler=$((zaehler+1))
  group=$(id -gn $login)
  sgroup=$(id -Gn $login | tr ' ' ',')
  sgroup=${sgroup#*,}

  echo -e "\n############ ${zaehler} ################"
  echo -e "\e[1mUser:\e[0m \e[31m\t\t\t${login}\e[0m"
  echo -e "\e[1mUUid:\e[0m \e[32m\t\t\t${uid}\e[0m"
  echo -e "\e[1mHome:\e[0m \e[33m\t\t\t${home}\e[0m"
  echo -e "\e[1mShell:\e[0m \e[34m\t\t\t${shell}\e[0m"
  echo -e "\e[1mprimäre Gruppe:\e[0m \e[35m\t${group}\e[0m"
  echo -e "\e[1mSekundäre Gruppe:\e[0m \e[36m\t${sgroup}\e[0m"

done < /etc/passwd

